README.md
next.config.js

Bug: https://bugs.webkit.org/show_bug.cgi?id=184447

fix(service worker): added some config to fix safari video issues

---

CHANGELOG.md
components/visualization/__snapshots__/visualization.spec.tsx.snap
components/visualization/visualization.spec.tsx
components/visualization/visualization.tsx
package-lock.json
package.json

Changes to linked content (i.e. the referenced blog posts) does not get updated straight away when visualising a blog list in DC

fix(blog list visualisation): delay in update of blog list visualisation

---

README.md

docs(readme): updated the content type schema installation process

---

README.md
common/interfaces/blog-list.interface.ts
common/interfaces/blog-post.interface.ts
common/interfaces/blog-reference-list.interface.ts
common/interfaces/blog.interface.ts
common/interfaces/content.type.ts
common/services/blog-list/get-blog-reference-list.service.ts
common/services/blog-list/get-hydrated-blog-list.service.ts
common/services/blog-post.service.ts
common/services/vse.service.spec.ts
common/services/vse.service.ts
components/blog-card/blog-card.tsx
components/blog-list/blog-list.spec.tsx
components/hero-card/hero-card.tsx
components/visualization/__fixtures__/blogpost.json
components/visualization/__snapshots__/visualization.spec.tsx.snap
components/visualization/visualization.spec.tsx
components/visualization/visualization.tsx
pages/index.tsx
schemas/blog-post.json
tests/fixtures/blog-list-one-blog-duplicate.json
tests/fixtures/blog-list-one-blog.json
tests/fixtures/single-blog-post-content-item.json
tests/fixtures/single-blog-post-data-object.json

Still referenced the urlSlug content item property 
- removed urlSlug and used the deliveryKey
- update BlogList to be Blog
- disabled the vizualisation component tests (awaiting changes)

feat(content-delivery-2): removed urlSlug property

---

README.md
common/services/get-index-name.spec.ts
common/services/get-index-name.ts
components/hero-card/__snapshots__/hero-card.spec.tsx.snap
components/hero-card/hero-card.tsx
components/search-result-list/__snapshots__/sort-by-dropdown.spec.tsx.snap
components/search-result-list/search-result-list.spec.tsx
components/search-result-list/search-result-list.tsx
components/search-result-list/sort-by-dropdown.spec.tsx
components/search-result-list/sort-by-dropdown.tsx

No sort by
- added algolia sort by (read time & datetime)
- updated readme
Branched from the keyword search branch

feat: algolia sort by dropdown

---

README.md

Missing section on how to set up a custom ranking for the primary index
- how to set up a custom ranking

docs(custom ranking): explain how to add a custom ranking to the primary index

---

components/header-search-box/header-search-box.tsx
components/search-result-list/__snapshots__/sort-by-dropdown.spec.tsx.snap
components/search-result-list/sort-by-dropdown.tsx

On smaller devices the search box input and sort by overlapped other elements in the page
Both components now display without overlapping other parts of the page on smaller devices

fix(header search): adding media query smaller device styles for search

---

components/header-search-box/__snapshots__/header-search-box.spec.tsx.snap
components/header-search-box/header-search-box.spec.tsx
components/header-search-box/header-search-box.tsx

When using Chrome shadow artefacts cover part of the page.
The box shadow has been remove from the search input box as this was causing the issue and was not an original requirement in the UX designs

fix(header search box): removing search input box shadow to resolve chrome bug

---

components/menu-select/menu-select.spec.tsx
components/menu-select/menu-select.tsx

Missing styles on dropdown menu in the Safari browser
Unified styling across all browsers

fix(menu select component): updated the styling to match across browsers

---

components/search-result-list/__snapshots__/sort-by-dropdown.spec.tsx.snap
components/search-result-list/sort-by-dropdown.tsx

Default sort option incorrectly set to none existent replica name and "sort by" repeated in options
Updated to use primary index as default sort option and removed "sort by" from the select option
Updated tests to reflect changes

fix(sortby menu): updates default sort options and labels

---

components/tag-chips/tag-chips.tsx
tests/pages/__snapshots__/blog.spec.tsx.snap

Cursor has an incorrect value and is not valid CSS
Updated to display the correct cursor
Updated the tests to reflect the change.

fix(tag chips): corrected the cursor property value to be a pointer

---

README.md

Existing README needed a few improvements
README changes only

docs(readme.md): UAT changes for readme

---

README.md

- content is indexed
- setup facet is duplicated
- content is removed from the index
- streamlined the configuring process

doc(readme): payload change & removed duplicated section

---

components/header-facet-bar/__snapshots__/header-facet-bar.spec.tsx.snap
components/header-facet-bar/header-facet-bar.tsx
components/hero-banner/__snapshots__/hero-banner.spec.tsx.snap
components/hero-banner/hero-banner.tsx
components/menu-select/menu-select.spec.tsx
components/menu-select/menu-select.tsx

The current hero banner are elements are a bit squashed
The hero banner has had some padding added to improve how hero banner elements are being displayed

fix(hero banner): adding additional spacing to elements in the hero banner

---

components/header-facet-bar/__snapshots__/header-facet-bar.spec.tsx.snap
components/header-facet-bar/header-facet-bar.tsx

Only shows 10 authors/tags
- Shows up to 25 authors and tags

fix: author and tags to display 25 items

---

components/blog-card/blog-card.spec.tsx
components/blog-card/blog-card.tsx

Delivery keys are incorrectly lowercased and are case sensitive in the API resulting in a page not being displayed.
The casing of a delivery key is now respected and there are some tests around the area.
Fixes: https://ampliencedev.atlassian.net/browse/TUP-2981

fix(blog card links): updated so that deliveryKey is not lowercase and added tests

---

components/content/__snapshots__/content.spec.tsx.snap
components/content/content.tsx
pages/blog/[...slug].tsx
tests/pages/__snapshots__/blog.spec.tsx.snap

Currently any "below the fold" content is lazy loaded.  This was initially put in place to improve page load performance.  However this has had a negative impact on search engine indexing as it prevent large portions of the pages text content from being searchable via search engines.
- Removed lazy loading component wrapper for text content so it can be indexed by search engines

feat(content): removing lazy loading for blog post text content

---

pages/_document.tsx

manifest.json is not loaded and causing console errors.
The manifest is now loaded correctly.

fix(manifest json): changed the link location for the manifest file

---

components/share-post/__snapshots__/share-post.spec.tsx.snap
components/share-post/share-post.tsx
tests/pages/__snapshots__/blog.spec.tsx.snap

Linkedin share button fails to load on blog post pages
Linkedin share button loads on blog post pages

fix(share post): removing linkedin placeholder script from helmet

---

README.md
components/microdata/__snapshots__/microdata.spec.tsx.snap
components/microdata/microdata.tsx

The microdata in the blog is using an ineligible schema type and therefore to improve SEO has been updated.
Added the article schema type to improve SEO and added some notes to the readme about hardcoded values.

fix(microdata): updated to use article type and added extra required information

---

next.config.js
package-lock.json
package.json
scripts/sitemap-generator.js

trailing slashes are missing from the sitemap.xml
- enabled trailing slashes in the sitemap.xml
- disabled the `withOffline` plugin as it's not compatible with the sitemap generator

fix: add trailling slashes to sitemap.xml

---

README.md

Previous custom payload led to malford JSON were the first item in the content array was an image or
video. Use the pluck helper to create an array of only text content.
Previous custom payload led to malford JSON were the first item in the content array was an image or
video. This is because there an extra line was generated containing just a comma.
Used the pluck helper to create an array of only text content, preventing above error.
-
-
-

docs(readme): updated example custom payload to minimise indexing errors

---

scripts/sitemap-generator.js

robots.txt doesn't include the sitemap reference
- adds the sitemap url to the robots.txt file during the export process

feat: add sitemap url to robots.txt
